CREATE DATABASE ecommerce;
USE ecommerce;
SHOW databases;
CREATE TABLE product (
	PRODUCT_CODE VARCHAR(20) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    ORI_PRICE INT,
    DISCOUNT_PRICE INT,
    DISCOUNT_PERCENT INT,
    DELIVERY VARCHAR(2),
    PRIMARY KEY(PRODUCT_CODE)
    );
desc product;
CREATE TABLE ranking (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	CATEGORY VARCHAR(50),
	SUBCATEGORY VARCHAR(50),
	RANKING INT NOT NULL,
	PRODUCT_CODE VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);
desc ranking;
INSERT INTO product values('213423352', '스위트비니',23000,6900,70,'F');
SELECT * FROM product