USE mydata;
DESC mytable;
INSERT INTO mytable VALUES(1,'i7','7700','Kaby Lake');
SELECT * FROM mytable;
INSERT INTO mytable (name, model_num, model_type) VALUES('i7','7700','Kaby Lake');
SELECT * FROM mytable;
ALTER TABLE mytable MODIFY model_type VARCHAR(30) NOT NULL;
INSERT INTO mytable (name,model_num, model_type) VALUES('i5','9600K','Coffee Lake Refresh');
INSERT INTO mytable (name,model_num, model_type) VALUES('i5','9400F','Coffee Lake Refresh');
INSERT INTO mytable (name,model_num, model_type) VALUES('i7','9700K','Coffee Lake Refresh');
INSERT INTO mytable (name,model_num, model_type) VALUES('i7','8700','Coffee Lake');
INSERT INTO mytable (name,model_num, model_type) VALUES('i5','8500','Coffee Lake');
SELECT * FROM mytable;
SELECT name FROM mytable;
SELECT name, model_num, model_type, id FROM mytable;
SELECT name AS cpu_name, model_num AS cpu_num FROM mytable;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable ORDER BY id DESC;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable ORDER BY id ASC;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable WHERE id < 3;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable WHERE id = 3;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable WHERE id > 3  and id < 7;
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable WHERE id < 3  or name = 'i7';
SELECT id, name AS cpu_name, model_num AS cpu_num FROM mytable WHERE name LIKE'%5%';
SELECT * FROM mytable WHERE model_type LIKE'%kaby%';
SELECT * FROM mytable WHERE model_type LIKE'kaby%';
SELECT * FROM mytable WHERE model_type LIKE'kaby_____';
SELECT * FROM mytable WHERE model_type LIKE'_______lake';
SELECT * FROM mytable WHERE model_type LIKE'_______lake' and id = 6;
SELECT * FROM mytable WHERE model_type LIKE'_______lake' or id = 1;
SELECT * FROM mytable LIMIT 5;
SELECT * FROM mytable LIMIT 2,2;
SELECT * FROM mytable WHERE id < 4 AND name LIKE '%i%' ORDER BY name DESC LIMIT 2;
SELECT * FROM mytable WHERE model_num LIKE '7700%';
SELECT * FROM mytable WHERE name = 'i7';
SELECT * FROM mytable WHERE model_type = 'Kaby Lake' LIMIT 1;
UPDATE mytable SET name = 'i3' WHERE id = 3;
UPDATE mytable SET name = 'i3', model_num='5500' WHERE id = 3;
SELECT * FROM mytable;
DELETE FROM mytable WHERE id = 2;
SELECT * FROM mytable;
ALTER TABLE mytable ADD COLUMN lowest_price INT UNSIGNED;
DESC mytable;
SELECT * FROM mytable;
UPDATE mytable SET lowest_price = 178860 WHERE id = 1;
SELECT * FROM mytable;
UPDATE mytable SET lowest_price = 645804 WHERE id = 3;
UPDATE mytable SET lowest_price = 234822 WHERE id = 4;
UPDATE mytable SET lowest_price = 545455 WHERE id = 5;
UPDATE mytable SET lowest_price = 897650 WHERE id = 6;
SELECT id, model_num FROM mytable WHERE lowest_price <= 300000;
SELECT * FROM mytable WHERE lowest_price >= 400000;